<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Expenses Report - {{ $report['reportDate'] }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; }
        th { background: #f5f5f5; }
        .summary { margin-bottom: 10px; }
        .small { font-size: 11px; color: #666; }
    </style>
</head>
<body>
<div class="header">
    <h2>Expenses Report</h2>
    <div class="small">Report Date: {{ $report['reportDate'] }} | From: {{ $report['dateRange']['from'] }} To: {{ $report['dateRange']['to'] }}</div>
    <div class="small">Generated By: {{ $report['generatedBy'] }} at {{ $report['generatedAt'] }}</div>
</div>

<div class="summary">
    <table>
        <tr><th>Total Expenses</th><td>{{ number_format($report['summary']['totalExpenses'], 2) }}</td></tr>
        <tr><th>Total Expense Count</th><td>{{ $report['summary']['totalExpenseCount'] }}</td></tr>
        <tr><th>Total Items</th><td>{{ $report['summary']['totalItems'] }}</td></tr>
    </table>
</div>

<h3>By Account</h3>
<table>
    <thead>
    <tr>
        <th>Account</th>
        <th>Total</th>
        <th>Count</th>
    </tr>
    </thead>
    <tbody>
    @foreach($report['summary']['byAccount'] as $acc)
        <tr>
            <td>{{ $acc['accountName'] }}</td>
            <td>{{ number_format($acc['total'], 2) }}</td>
            <td>{{ $acc['count'] }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<h3>Expenses</h3>
@foreach($report['expenses'] as $expense)
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Account</th>
            <th>Description</th>
            <th>Expense Date</th>
            <th>Reference</th>
            <th>Subtotal</th>
            <th>Tax</th>
            <th>Discount</th>
            <th>Total</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ $expense['id'] ?? '' }}</td>
            <td>{{ $expense['accountName'] ?? '' }}</td>
            <td>{{ $expense['description'] ?? '' }}</td>
            <td>{{ $expense['expenseDate'] ?? '' }}</td>
            <td>{{ $expense['reference'] ?? '' }}</td>
            <td>{{ $expense['subtotal'] ?? '' }}</td>
            <td>{{ $expense['tax'] ?? '' }}</td>
            <td>{{ $expense['discount'] ?? '' }}</td>
            <td>{{ $expense['total'] ?? '' }}</td>
            <td>{{ $expense['status'] ?? '' }}</td>
        </tr>
        </tbody>
    </table>

    <table>
        <thead>
        <tr>
            <th>Item Description</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Total</th>
            <th>Taxed</th>
        </tr>
        </thead>
        <tbody>
        @foreach($expense['items'] as $item)
            <tr>
                <td>{{ $item['description'] ?? '' }}</td>
                <td>{{ $item['quantity'] ?? '' }}</td>
                <td>{{ $item['unitPrice'] ?? '' }}</td>
                <td>{{ $item['total'] ?? '' }}</td>
                <td>{{ isset($item['taxed']) ? ($item['taxed'] ? 'Yes' : 'No') : '' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endforeach

</body>
</html>
